### PR TITLE
MaV_Tap2Earn - Readme.md

### PR DESCRIPTION
**Pull request by xxScorpius97xx**
Add latest readme for SimpleHTMLGame/MaV_Tap2Earn

### CODE REVIEW

**Comment by Normalnoise** [comment]
please update your title, and add a `readme.md` in your project folder; `readme.md` should include lagrange space link and running screenshot

**Comment by xxScorpius97xx** [comment]
It's already there

**Comment by xxScorpius97xx** [comment]
But this is the readme.md for #151

**Comment by Normalnoise** [comment]
please add all files to one PR

**Pull request closed without merging**
